version: '3.8'

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    environment:
      - AZURE_TABLES_CONNECTION_STRING=${AZURE_TABLES_CONNECTION_STRING}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    security_opt:
      - seccomp=unconfined  # Required for Chrome in Docker
    shm_size: '2gb'
    volumes:
      - /dev/shm:/dev/shm  # Shared memory access
    deploy:
      resources:
        limits:
          memory: 1G  # Increased for Chrome
          cpus: '1'
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
